using System;using System.Collections.Generic;using System.IO;using System.Linq;using System.Text;
namespace CommunityPoke.UnityGit {
 public sealed class Change {public string Path{get;set;} public string State{get;set;} }
 public sealed class Repository {public string Root{get;} public string GitDir=>Path.Combine(Root,".git");public LooseObjectStore Objects{get;} Repository(string root){Root=root;Objects=new LooseObjectStore(GitDir);}
 public static Repository Init(string root){Directory.CreateDirectory(root);var gd=Path.Combine(root,".git");Directory.CreateDirectory(Path.Combine(gd,"objects"));Directory.CreateDirectory(Path.Combine(gd,"refs","heads"));File.WriteAllText(Path.Combine(gd,"HEAD"),"ref: refs/heads/main\n");File.WriteAllText(Path.Combine(gd,"config"),"[core]\n\trepositoryformatversion = 0\n\tfilemode = false\n\tbare = false\n");return new Repository(root);}
 public static Repository Open(string path){var d=Directory.Exists(path)?new DirectoryInfo(path):new DirectoryInfo(Path.GetDirectoryName(path));while(d!=null&&!Directory.Exists(Path.Combine(d.FullName,".git")))d=d.Parent;if(d==null)throw new DirectoryNotFoundException("No Git repository found");return new Repository(d.FullName);}
 public string Branch{get{var h=File.ReadAllText(Path.Combine(GitDir,"HEAD")).Trim();return h.StartsWith("ref: refs/heads/")?h.Substring(16):h;}}
 public GitIndex Index=>GitIndex.Read(Path.Combine(GitDir,"index"));
 public void Add(string relativePath){relativePath=relativePath.Replace('\\','/');var full=Path.Combine(Root,relativePath);if(!File.Exists(full))throw new FileNotFoundException(relativePath);var bytes=File.ReadAllBytes(full);var hash=Objects.Write(new Blob(bytes));var idx=Index;var e=idx.Entries.FirstOrDefault(x=>x.Path==relativePath);if(e==null){e=new GitIndexEntry{Path=relativePath};idx.Entries.Add(e);}e.Hash=hash;e.Mode=Convert.ToUInt32("100644",8);idx.Write(Path.Combine(GitDir,"index"));}
 public IReadOnlyList<Change> Status(){var changes=new List<Change>();var idx=Index;foreach(var e in idx.Entries){var f=Path.Combine(Root,e.Path);if(!File.Exists(f))changes.Add(new Change{Path=e.Path,State="deleted"});else if(GitHash.Compute("blob",File.ReadAllBytes(f))!=e.Hash)changes.Add(new Change{Path=e.Path,State="modified"});}var known=new HashSet<string>(idx.Entries.Select(e=>e.Path));foreach(var f in Directory.GetFiles(Root,"*",SearchOption.AllDirectories)){if(f.Contains(Path.DirectorySeparatorChar+".git"+Path.DirectorySeparatorChar))continue;var rel=f.Substring(Root.Length+1).Replace('\\','/');if(!known.Contains(rel))changes.Add(new Change{Path=rel,State="untracked"});}return changes;}
 public string Commit(string message,string author="UnityGit User <unitygit@example.com>"){var entries=Index.Entries.Select(e=>new TreeEntry(e.Mode.ToString("o"),e.Path,e.Hash));var tree=Objects.Write(new Tree(entries));var headPath=Path.Combine(GitDir,"HEAD");var head=File.ReadAllText(headPath).Trim();var refPath=head.StartsWith("ref: ")?Path.Combine(GitDir,head.Substring(5).Replace('/',Path.DirectorySeparatorChar)):null;var parents=new List<string>();if(refPath!=null&&File.Exists(refPath))parents.Add(File.ReadAllText(refPath).Trim());var ident=author+" "+DateTimeOffset.UtcNow.ToUnixTimeSeconds()+" +0000";var hash=Objects.Write(new Commit(tree,parents,ident,message));if(refPath!=null){Directory.CreateDirectory(Path.GetDirectoryName(refPath));File.WriteAllText(refPath,hash+"\n");}return hash;}
 public IEnumerable<string> Log(){var h=File.ReadAllText(Path.Combine(GitDir,"HEAD")).Trim();var p=h.StartsWith("ref: ")?Path.Combine(GitDir,h.Substring(5).Replace('/',Path.DirectorySeparatorChar)):null;if(p==null||!File.Exists(p))yield break;var hash=File.ReadAllText(p).Trim();while(!string.IsNullOrEmpty(hash)){yield return hash;var o=Objects.Read(hash);var text=Encoding.UTF8.GetString(o.data);var line=text.Split('\n').FirstOrDefault(x=>x.StartsWith("parent "));hash=line==null?null:line.Substring(7);}}
 }
}